config/routes.rb
Rails.application.routes.draw do
  resources :rooms do
    resources :messages
    collection do
      post :search
    end
  end

  get 'rooms/leave/:id', to: 'rooms#leave', as: 'leave_room'
  get 'rooms/join/:id', to: 'rooms#join', as: 'join_room'

  root 'pages#home'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  
  get 'user/:id', to: 'users#show', as: 'user'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_nav.html.erb
<div id="single_room" class="bg-gray-800 chat-header flex sm:items-center justify-between py-3 border-gray-200">
  <div>
  <%= link_to root_path do %>
    <%= image_tag("swissfit.png", class: "logo w-10 ml-3") %>
  <%end%>

  </div>
  <% if current_user %>
  <div class="flex items-center space-x-2">
    <%= button_to destroy_user_session_path, method: :delete, class:"inline-flex items-center justify-center rounded-full h-10 w-10 transition duration-500 ease-in-out text-gray-500 hover:bg-gray-300 focus:outline-none" do%>
      <i class="ri-logout-box-line text-xl"></i>
    <% end %>
    <%= link_to edit_user_registration_path, class:"inline-flex items-center justify-center rounded-full h-10 w-10 transition duration-500 ease-in-out text-gray-500 hover:bg-gray-300 focus:outline-none" do %>
      <i class="ri-account-circle-fill text-xl"></i>
    <%end%>
  </div>
  <%end%>
</div>

app/views/shared/_new_message_form.html.erb
<%= form_with(model: [@single_room, @message], remote: true, data: {controller: "reset-form", action: "turbo:submit-end->reset-form#reset"}, multipart: true) do |f| %>
  <div class="w-full px-4 pt-4 mb-2 sm:mb-0">
    <div class="relative flex">
      <div class="w-full">
        <div id="attachment-previews" class="d-none" data-controller="message-preview" data-action="message-preview#preview"></div>
        <div>
          <span class="flex items-center">
            <%= f.file_field :attachments, multiple: true, data: {controller: "message-preview", action: "change->message-preview#preview"} %>
          </span>
          <div style="margin-top: 10px;">
            <%= f.text_area :body, id: 'chat-text', placeholder: "Write your message!", class: "my-4 block mx-4 p-2.5 w-full text-sm text-gray-900 bg-white rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500" %>
          </div>
        </div>
        <div class="mb-3">
          <%= f.submit "Send", data: {disable_with: false}, class: "inline-flex justify-center p-2 text-indigo-600 rounded-full cursor-pointer hover:bg-indigo-100" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_new_room_form.html.erb
<% if current_user.admin? %>
  <%= form_with(model: @room, remote: true, class: "d-flex", data: {controller: "reset-form", action: "turbo:submit-end->reset-form#reset"}) do |f| %>
    <div class="flex">
      <%= f.text_field :name, class:"bg-gray-700 focus:outline-none focus:ring-1 focus:ring-gray-100 rounded w-full text-sm text-gray-300 placeholder-gray-400 bg-gray-100 pl-5 py-2", autocomplete: "off" %>
      <%= f.submit "create", data: {disable_with: false}, class:" my-2 bg-white transition duration-150 ease-in-out rounded text-gray-800 border border-gray-300 px-3 py-2 text-xs hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-offset-2  focus:ring-gray-800"  %>
    </div>
  <%end%>
<%end%>

app/views/shared/_room_template.html.erb
<div class="mt-12">
  <h5 class="text-center user-title">Users</h5>
  <%= turbo_stream_from "users" %>
  <div id="users">
    <%= render @users%>
  </div>
</div>
<div class="flex justify-center mt-48 mb-4 w-full">
  <div class="relative">                  
    <h5 class="text-center mb-3 room-title ">Rooms</h5>
    <%= render 'shared/new_room_form'%>
    <%= render 'shared/search_form'%>
    <%= turbo_stream_from "rooms" %>
    <div id="rooms">
      <%= render @joined_rooms %>
    </div>                    
  </div>
</div>

app/views/shared/_search_form.html.erb
<%= form_with url: search_rooms_path, method: :post, id: "room_search_form", data: {controller: "debounce"} do |form| %>
  <%= form.search_field :name_search, 
    value: params[:name_search],
    class: "bg-gray-700 focus:outline-none focus:ring-1 focus:ring-gray-100 rounded w-full text-sm text-gray-300 placeholder-gray-400 bg-gray-100 pl-5 py-2", 
      placeholder: "Search Rooms to Join...",
    data: { action: "input->debounce#search"} %>
<% end %>
<div id="search_results">
  <%= render 'rooms/search_results', rooms: @rooms %>
</div>