config/routes.rb
Rails.application.routes.draw do
  resources :rooms do
    resources :messages
    collection do
      post :search
    end
  end

  get 'rooms/leave/:id', to: 'rooms#leave', as: 'leave_room'
  get 'rooms/join/:id', to: 'rooms#join', as: 'join_room'

  root 'pages#home'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  
  get 'user/:id', to: 'users#show', as: 'user'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/room.rb
class Room < ApplicationRecord
  validates_uniqueness_of :name
  scope :public_rooms, -> { where(is_private: false) }
  after_create_commit { broadcast_if_public }
  has_many :messages
  has_many :participants, dependent: :destroy
  has_many :joinables, dependent: :destroy
  has_many :joined_users, through: :joinables, source: :user

  def broadcast_if_public
    broadcast_latest_message
  end

  def self.create_private_room(users, room_name)
    single_room = Room.create(name: room_name, is_private: true)
    users.each do |user|
      Participant.create(user_id: user.id, room_id: single_room.id)
    end
    single_room
  end

  def participant?(room, user)
    room.participants.where(user: user).exists?
  end

  def latest_message
    messages.includes(:user).order(created_at: :desc).first
  end

  def broadcast_latest_message
    last_message = latest_message

    return unless last_message

    room_target = "room_#{id} last_message"
    user_target = "room_#{id} user_last_message"
    sender = Current.user.eql?(last_message.user) ? Current.user : last_message.user

    broadcast_update_to('rooms',
                         target: room_target,
                         partial: 'rooms/last_message',
                         locals: {
                           room: self,
                           user: last_message.user,
                           last_message: last_message
                         })
    broadcast_update_to('rooms',
                         target: user_target,
                         partial: 'users/last_message',
                         locals: {
                           room: self,
                           user: last_message.user,
                           last_message: last_message,
                           sender: sender
                         })
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  include RoomsHelper
  before_action :authenticate_user!
  before_action :set_status

  def index
    @room = Room.new
    @joined_rooms = current_user.joined_rooms.order('last_message_at DESC')
    @rooms = search_rooms
    current_user.update(current_room: nil)
    @users = User.all_except(current_user)
    render 'index'
  end

  def show
    @single_room = Room.find(params[:id])
    current_user.update!(current_room: @single_room)
    @room = Room.new
    @rooms = search_rooms
    @joined_rooms = current_user.joined_rooms.order('last_message_at DESC')

    @message = Message.new
    @messages = @single_room.messages.order(created_at: :asc)

    @users = User.all_except(current_user)
    render 'index'
  end

  def create
    @room = Room.create(room_params)
    redirect_to rooms_path
  end


  def search
    @rooms = search_rooms
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.update(
            'search_results',
            partial: 'rooms/search_results',
            locals: {
              rooms: @rooms
            }
          )
        ]
      end
    end
  end

  def join
    @room = Room.find(params[:id])
    current_user.joined_rooms << @room
    redirect_to room_path
  end

  def leave
    @room = Room.find(params[:id])
    current_user.joined_rooms.delete(@room)
    redirect_to rooms_path
  end

  private
  
  def room_params
    params.require(:room).permit(:name, :is_private)
  end

  def set_status
    current_user.update!(status: User.statuses[:offline]) if current_user
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
  def search_rooms
    if params.dig(:name_search).present? && params.dig(:name_search).length > 0
      Room.public_rooms
          .where
          .not(id: current_user.joined_rooms.pluck(:id))
          .where('name ILIKE ?', "%#{params.dig(:name_search)}%")
          .order(name: :asc)
    else
      []
    end
  end

  def get_name(user1, user2)
    user = [user1, user2].sort
    "private_#{user[0].id}_#{user[1].id}"
  end
end

app/views/rooms/_joinable_link.html.erb
<% if current_user.has_joined_room(room)%>
  <%= link_to leave_room_path(room), method: :delete, data:{turbo: "false"} do %>
    <i class="ri-chat-delete-line text-lg text-gray-300"></i>
  <%end%>
<%else%>
  <%= link_to join_room_path(room), method: :delete, data:{turbo: "false"} do %>
    <i class="ri-add-circle-fill text-lg text-gray-300"></i>
  <%end%>
<%end%>

app/views/rooms/_last_message.html.erb
<% unless last_message.nil? %>
  <div class="row">
    <div class=" text-white text-xs">
      <div>
        <em class="last-message">
          <%= "#{last_message.user.username}: #{last_message.body}".truncate(40) %>
        </em>
      </div>
      <div>
        <%= content_tag(:em, class:"last-message-time", 
          data: {
            time: last_message.created_at.to_i
            }) do %>
              
          <%= "#{time_ago_in_words(last_message.created_at)} ago"%>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/rooms/_room.html.erb
<%if room.id.eql?(current_user.current_room) %>
  <% isActive = "active" %>
<%else%>
  <% isActive = "" %>
<%end%>
<div class="room">
    <div class="flex flex-row items-center user-val rounded-xl p-2 <%= isActive%>">
      <div class="text-sm font-semibold">
        <%= turbo_frame_tag dom_id(room) do %>
          <%= link_to room.name, room_path(room, name_search: params[:name_search]), data: {turbo: "false"}, class:"room-text" %>
        <%end%>
        <%= render 'rooms/joinable_link', room: room %>
      </div>
    </div>
    <%= turbo_frame_tag [dom_id(room), "last_message"] do %>
      <%= render 'rooms/last_message',  
        last_message: last_message,
        user: user,
        room: room
      %>
    <% end %>
</div>

app/views/rooms/_room_container.html.erb
<div class="flex flex-row items-center user-val rounded-xl p-2 <%isActive%>">
  <div class="text-sm font-semibold">
      <%= link_to room.name, room_path(room, name_search: params[:name_search]), data: {turbo: "false"}, class:"room-text" %>
    <%= render 'rooms/joinable_link', room: room %>
  </div>
</div>

<%= turbo_frame_tag [dom_id(room), "last_message"] do %>
  <%= render 'rooms/last_message',
    room: room,
    last_message: last_message, 
    user: user
  %>
<% end %>

app/views/rooms/_rooms.html.erb
<% rooms.each do |room| %>
  <%= render 'rooms/room',
    room: room,
    last_message: room.latest_message, 
    user: user 
  %>
<% end %>

app/views/rooms/_search_results.html.erb
<%rooms.each do |room|%>
  <div class="flex flex-row items-center user-val rounded-xl p-2">
    <div class="text-sm font-semibold">  
      <%= link_to room.name, room_path(id: room.id, name_search: params[:name_search]), data: {turbo: "false"}, class:"room-text" %>
      <%= render 'rooms/joinable_link', room: room %>
    </div>
  </div>
<%end%>

app/views/rooms/index.html.erb
<%= turbo_frame_tag "appearance_channel"%>
<div id="appearance_channel"></div>

  <div id="chatroom_container" class="w-full h-full">
    <div class="flex flex-no-wrap">
      <div class="w-64 z-40 absolute bg-gray-800 shadow md:h-full flex-col justify-between transition duration-150 ease-in-out" id="mobile-nav"  style="height: 1116px;"  data-controller="sidebar" data-sidebar-target="sidebar">
        <div style="margin-top: -59px;">  
          <button 
          data-action="click->sidebar#toggleSidebar"
          data-sidebar-target="openButton"
          aria-label="toggle sidebar" id="openSideBar" class="h-10 w-10 bg-gradient-to-r from-green-400 to-blue-500 hover:from-pink-500 hover:to-yellow-500 absolute right-0 mt-16 -mr-10 flex items-center shadow rounded-tr rounded-br justify-center cursor-pointer focus:outline-none focus:ring-2 focus:ring-offset-2 rounded focus:ring-gray-800" >
          <svg  xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-adjustments" width="20" height="20" viewBox="0 0 24 24" stroke-width="1.5" stroke="#FFFFFF" fill="none" stroke-linecap="round" stroke-linejoin="round">
            <path stroke="none" d="M0 0h24v24H0z" />
            <circle cx="6" cy="10" r="2" />
            <line x1="6" y1="4" x2="6" y2="8" />
            <line x1="6" y1="12" x2="6" y2="20" />
            <circle cx="12" cy="16" r="2" />
            <line x1="12" y1="4" x2="12" y2="14" />
            <line x1="12" y1="18" x2="12" y2="20" />
            <circle cx="18" cy="7" r="2" />
            <line x1="18" y1="4" x2="18" y2="5" />
            <line x1="18" y1="9" x2="18" y2="20" />
          </svg>
        </button>
        <button 
          data-action="click->sidebar#toggleSidebar"
          data-sidebar-target="closeButton"
          aria-label="Close sidebar" id="closeSideBar" class="hidden h-10 w-10 bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 absolute right-0 mt-16 -mr-10 flex items-center shadow rounded-tr rounded-br justify-center cursor-pointer text-white" >
          <svg  xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-x" width="20" height="20" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
            <path stroke="none" d="M0 0h24v24H0z" />
            <line x1="18" y1="6" x2="6" y2="18" />
            <line x1="6" y1="6" x2="18" y2="18" />
          </svg>
        </button>
        </div>
        <div class="px-8">
          <div class="h-16 w-full flex items-center" style="padding-top: 56px;">
            <h3 class="text-white font-mono" style="margin-top: 10px;">Swissfit</h3>
          </div>
          <div class="flex flex-col items-center bg-gradient-to-r from-indigo-500 from-10% via-sky-500 via-30% to-emerald-500 to-90% border border-gray-100 mt-4 w-full py-6 px-4 rounded-lg">
            <div class="h-20 w-20 rounded-full border overflow-hidden">
              <%= image_tag(current_user.avatar_thumbnail,class:"h-full w-full")%>
            </div>
            <div class=''>
              <%= render "users/status", user: current_user %>
            </div>
            <div class="text-sm font-semibold mt-2"><%= current_user.username%></div>
            <div class="text-xs text-gray-500"><%= current_user.email%></div>
          </div>
          <div class="mt-12">
            <h5 class="text-center user-title">Users</h5>
            <%= turbo_stream_from "users" %>
            <div id="users" data-controller="user-list">
              <%= render "users/users", users: @users %>
            </div>
          </div>
          <div class="flex justify-center mt-5 mb-4 w-full">
            <div class="relative">                  
              <h5 class="text-center mb-3 room-title ">Rooms</h5>
              <%= turbo_stream_from "rooms" %>
              <%= render 'shared/new_room_form'%>
              <%= render 'shared/search_form'%>
             
              <div id="rooms" data-controller="room-list">
                <%= render 'rooms/rooms', rooms: @joined_rooms, user: current_user %>
              </div>                    
            </div>
          </div>
        </div>
    </div>
    
    <div id="room_container" class="w-full flex-1 p:2 flex flex-col h-screen chat-room-cont" style="height: 1122px;">
      <% if @single_room %>
        <div>
          <h4 class="text-xl header-text text-center ">
            <%=@user&.username || @single_room.name %>
          </h4>
        </div>
        <%=turbo_stream_from @single_room %>      
        <div id="messages" data-controller="scroll" class="flex flex-col space-y-4 p-3 overflow-y-auto scrollbar-thumb-blue scrollbar-thumb-rounded scrollbar-track-blue-lighter scrollbar-w-2 scrolling-touch">
          <%= render @messages %>
        </div>
        <%= render 'shared/new_message_form'%>
      <%end%>
    </div>
  </div>
</div>